### ISSUE TITLE
Add custom port list

### ISSUE THREAD

**Issue by NoamRotter** [proferosec/log4jScanner#105]
Please add an option to define specific ports.

**Comment by slingr-dev** [comment]
I was trying to use this tool on a custom port earlier and had to revert to a different tool. This suggestion would be great if implemented.

**Comment by guybarnhartmagen** [comment]
we are adding the option for a custom port list in the next version

**Comment by guybarnhartmagen** [comment]
@hagarze can we please add the option for the following to `--ports`:
* top10
* top100
* slow (currently disabled)
* single port (e.g. 9000)
* port range separated by colon (e.g. 9000:9004)

**Comment by guybarnhartmagen** [comment]
@hagarze let's remove the "slow" option at the moment, and limit port ranges to 1024 at most

**Comment by guybarnhartmagen** [comment]
fixed in version `0.3.1`

**Comment by NoamRotter** [comment]
Thanks !
