### ISSUE TITLE
Option to scan IP lists not just ranges

### ISSUE THREAD

**Issue by styxnixcabbage** [proferosec/log4jScanner#106]
Could you add the option to scan IP lists and not just ranges?

**Comment by jtopoleski** [comment]
Even an option to scan a list of ranges would be nice actually for subnets and the like

**Comment by guybarnhartmagen** [comment]
well - we thought that you can scan multiple subnets by either running the tool through a bash script (parallel or in sequence)

did you mean something else?

**Comment by guybarnhartmagen** [comment]
@styxnixcabbage as a general rule we decided that we dont want to create dependencies on external files at this stage. you can run the tool through a bash script to support a list of subnets, and I think that can solve this issue

thank you for submitting
