### ISSUE TITLE
Add ability to pick TCP server port with a switch

### ISSUE THREAD

**Issue by jtopoleski** [proferosec/log4jScanner#107]
in order to cover my network quickly enough it would be useful to be able to run multiple instances of this on different ports, especially if the list of IP ranges is implemented as I could split up the list too.

**Comment by xFreed0m** [comment]
Hey @jtopoleski 

You can do this now using the `--server` flag, use it with IP:PORT to choose the listening address and the desired port.

**Comment by xFreed0m** [comment]
See this example
`log4jscanner.exe scan --cidr 192.168.7.0/24 --server=192.168.1.100:5000`
