### ISSUE TITLE
APIPA and general question 

### ISSUE THREAD

**Issue by diyarit** [proferosec/log4jScanner#125]
Hi there, is that the normal behavior? and do I need to start a listener or just run the tool on the entire network and see what's vulnerable?

![image](https://user-images.githubusercontent.com/30482423/146718158-ad475175-61f1-44b8-bdf8-2ed12715c6cc.png)

**Comment by guybarnhartmagen** [comment]
this looks like normal behavior. the tool listens on 0.0.0.0:5555 so make sure it is open for incoming requests. the tool will scan the network for open ports and will try to send them requests. if there are any callbacks, they will be logged with the IP and port of the vulnerable service.

you can also look at the video in the main page for an example
