### ISSUE TITLE
Add ability to scan custom lists of Ports

### ISSUE THREAD

**Issue by Ach13v3-M0n7** [proferosec/log4jScanner#135]
While there is functionality to scan the "Top 100" and scan port ranges, the ability to scan custom lists of individual ports, similar to nmap would be extremely useful.

For instance, the following syntax would scan the ports 1, 2, 5, and 7 (numbers just examples):
`--ports=1,2,5,7`

This would allow targeted scans of environments based off of the open ports found using other tools. With the `--ports=top100` option, it takes about 15 minutes to get through a /24 in my experience. The speed of the scan is quickly prohibitive when trying to scan 100s if not 1000s of ports.

Being able to list individual ports in a list would prevent the need from kicking off many scans or scanning big ranges of ports when only certain ports are known to be open.

**Comment by guybarnhartmagen** [comment]
@hagarze can we easily add this to the port flag parsing? i worry that the flag list might be too long

**Comment by Ach13v3-M0n7** [comment]
Worst case, I can edit the values assigned to one of the variables in ports_consts file.

**Comment by guybarnhartmagen** [comment]
That's possible, but we will release a version with this addition soon :-)
