### ISSUE TITLE
Feature Request: Instead of cidr a possibility to scan one specific IP address

### ISSUE THREAD

**Issue by Karmakstylez** [proferosec/log4jScanner#142]
Can you please add the feature to scan only 1 specific IP adres instead of a subnet of IP addresses?

E.g. `.\log4jScanner-v0.3.3.exe scan --cidr 127.0.0.1`

PS: Also maybe the option to scan an URL instead of an IP address? 

E.g. `.\log4jScanner-v0.3.3.exe scan --cidr localhost.org`

**Comment by xFreed0m** [comment]
You can do it now, by putting the ip and /32 in the end, the cidr for a single host (:

**Comment by Karmakstylez** [comment]
@xFreed0m 

How about URLs? Is that also an option? Or do I need to make the translation to the IP address first?

**Comment by xFreed0m** [comment]
Currently the tool only supports IPs, you will need to make the translation first.
